### PR TITLE
added default type to discriminator attribute

### PR DESCRIPTION
**Pull request by DanielDavis5**

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
@DanielDavis5 Do you have a use case in mind for this? Normally when you use a discriminator it's expected all of the child types are known and mapped.

**Comment by DanielDavis5** [comment]
@Blacksmoke16 Right so, the abridged version is my test case also illustrates the use case. 

The issue is with the assertion that **all of the child types are known and mapped**. In spirit I understand what you are saying, but to be technical that is still the case. There is still a known and finite set of derivative types. It just so happens that one type, the default type, is defined by a negation similar to what the **"_ ->"** symbol represents in many pattern matching syntax.

An answer as to why you would do this is, if your models are data-driven it's possible to have an indeterminate and/or dynamic set of data models that still have a generalized abstraction. Both a triangle and a square are polygon and all polygons have vertices. There is also an infinite number of different types of polygons. Some that have yet to be given a proper name. One could, of course, just have explicit discrimination to the **"Polygon"** type but that would require serialization to encode that at a loss of information. To recover you would have to add another descriptor, for example say polygon_type. This solution is obtuse and exist for no other reason other than as a limitation of the framework.

**Comment by Blacksmoke16** [comment]
> Both a triangle and a square are polygon and all polygons have vertices. There is also an infinite number of different types of polygons. Some that have yet to be given a proper name.

I think I still don't fully understand why `GenericPolygon` couldn't just be part of the map. E.g. as a `default` or `generic_polygon` key? This way you still in the world of **all of the child types are known and mapped**.

I also think it's important to differentiate that the type of the object does not always necessarily map to its name. E.g. in the specs:

```json
{
  "type":"quadrilateral",
  "vertices":[
    {"type":"point","x":0,"y":0},
    {"type":"point","x":1,"y":0},
    {"type":"point","x":0,"y":1},
    {"type":"point","x":1,"y":1}
  ]
}
```
Could be better modeled as: 

```json
{
  "name": "quadrilateral",
  "type":"generic_polygon",
  "vertices":[
    {"type":"point","x":0,"y":0},
    {"type":"point","x":1,"y":0},
    {"type":"point","x":0,"y":1},
    {"type":"point","x":1,"y":1}
  ]
}
```
In that it is a `quadrilateral` shape, but is using the generic polygon type.

**Comment by DanielDavis5** [comment]
That is the solution I described at the end of my last post. I assume you mean it is better because it is more explicit which I would agree from a strict de-serialization context. However, as an end user who's models are data-driven I do not care about the underlying type. The first level discriminator was superfluous and I would not like it in my data.

```
{
  "type":"quadrilateral",
  "vertices":[
    {"type":"point","x":0,"y":0},
    {"type":"point","x":1,"y":0},
    {"type":"point","x":0,"y":1},
    {"type":"point","x":1,"y":1}
  ]
}
```
Seems much nicer than,

```
{
  "name": "quadrilateral",
  "type":"generic_polygon",
  "vertices":[
    {"type":"point","x":0,"y":0},
    {"type":"point","x":1,"y":0},
    {"type":"point","x":0,"y":1},
    {"type":"point","x":1,"y":1}
  ]
}
```

Does it not?

What would be the argument for explicitly specifying the abstraction in the data? Do you believe that having the direct name in the map makes the model schema more powerful?

**Comment by Blacksmoke16** [comment]
> The first level discriminator was superfluous and I would not like it in my data.

Sorry if it wasn't clear but the `name` property was just there as something all shapes would have and is _NOT_ related to deserialization. It could be made optional (or derived from the type if it's not generic) if you have anonymous unnamed shapes as well. I just wanted to point out that tightly coupling your data modeling with the deserialization logic might not be the way to go.

Like from a deserialization point of view the JSON payload does not technically represent a `Quadrilateral` type, but a `GenericPolygon` type. This type _could_ have a name of `quadrilateral`, but that is still different than its type. By introducing a default, it's essentially the same as deserializing `Polygon | GenericPolygon` (which currently works in this example we been using).

In the end I guess im proposing to just move the default into a map that has an explicit key:

```json
{
  "type":"generic_polygon",
  "vertices":[
    {"type":"point","x":0,"y":0},
    {"type":"point","x":1,"y":0},
    {"type":"point","x":0,"y":1},
    {"type":"point","x":1,"y":1}
  ]
}
```

This way it's no more verbose than any other type in the map while not requiring any other features. E.g. `@[ASRA::Discriminator(key: "type", map: {"triangle" => Triangle, "generic_polygon" => GenericPolygon)]`.

**Comment by DanielDavis5** [comment]
>  I just wanted to point out that tightly coupling your data modeling with the deserialization logic might not be the way to go.

That's somewhat my point exactly. Using **generic_polygon** as the data type is simply a way to placate the deserializer. So you would be designing your models to adhere to a framework constraint. That is weak coupling.

Additionally, the solution you have suffers from what I pointed out earlier as a **loss of information**; the information lost was the **name** of that type of polygon. If your model were an API endpoint the client would be required to implement some kind of convoluted resolution logic to re-determine that this instance is indeed a Quadrilateral. Again, you could add back in the name as an additional parameter, as you did in your previous example, but that just goes back to having data that just doesn't need to be there and exist only to facilitate deserialization.

Does that make sense?

**Comment by Blacksmoke16** [comment]
> but that just goes back to having data that just doesn't need to be there and exist only to facilitate deserialization.

> If your model were an API endpoint the client would be required to implement some kind of convoluted resolution logic to re-determine that this instance is indeed a Quadrilateral.

But the name has nothing to do with deserialization. In the eyes of deserialization, the data you're providing the type as `generic_polygon` and it's transformed into a `GenericPolygon` which makes sense. The name soley exists to represent what a non-mapped generic polygon is. And isn't this example a bit contrived since the `Quadrilateral` type would most likely exist in the map along with other common shapes? The default, and by extension, the `generic_polygon` would primarily be used for shapes that do not have a well defined name.

I still think a more ideal implementation would be more like:

```cr
@[ASRA::Discriminator(key: "type", map: {"triangle" => Triangle, "generic_polygon" => GenericPolygon)]
abstract class Polygon
  include ASR::Serializable

  getter type : String

  def name : String
    @type
  end
end

class Triangle < Polygon
  property p1 : Point
  property p2 : Point
  property p3 : Point
end

class GenericPolygon < Polygon
  property vertices : Array(Point)
  getter name : String
end
```

This doesn't require any new features. It also derives the name of the shape from its type if its an explicit one, otherwise an additional `name` property is required to be included.

Yes this does require _one_ extra property in the generic context, but not a huge deal given the extra clarity it provides. I.e. it is clear the data represents the `GenericPolygon` type with an arbitrary name versus an standardized shape of a specific type.

**Comment by DanielDavis5** [comment]
Sorry for drawing that out, I just want to make sure you understood the capability. I believe you do understand and do not agree to it's usefulness. That is fair and as such feel free to close the PR or I can if you would like. Thanks for looking into it.

However, I would like to point out that the _one_ extra property can be a big deal to some; the reasons I have already specified. Additionally, specifying the abstraction (i.e.: `GenericPolygon`) **only** provides clarity if you ignore the context. I think it's clear that we are both talking about these example types in somewhat of a geometric domain. With that known, it is without a doubt a fact that triangles, squares, etc... are all polygons and that fact in no way needs to be specified. No more so than saying, for instance, that any particular instance is an `Object`.

Feel free to reach out if you have any questions.

**Comment by Blacksmoke16** [comment]
I appreciate the contribution, sorry it didn't work out. Feel free to stop by the Athena Gitter/Discord if you'd like to chat about anything else: https://athenaframework.org/#resources.

> are all polygons and that fact in no way needs to be specified

Right yea, if they are in the discriminator map as a dedicated types then things just work as you want them to. It's only when you want to deserialize non-standardized shapes that the extra `name` property comes into play. Of course you could do like `class Triangle < Polygon`, `class Square < Polygon` in order to share that logic But to your point, if you just want to deserialize polygons you could also just use `class Polygon` directly and have it include a `type` property and don't even both with the discriminator map. Or worst case do `.deserialize Polygon | GenericPolygon`.

**Pull request closed without merging**
